name: check_pull_request_branch_type

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [main]

jobs:
  check_pr_branch_type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Distinguish branch type
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          branch_prefix=$(echo ${{ env.BRANCH_NAME }} | cut -d '/' -f1)
          
          case "$branch_prefix" in
            # These are the normally used branch prefixes
            "release"|"feature"|"hotfix"|"patch")
              acceptable_prefix=true
              ;;
            
            # These are the special exceptions
            "gh-action")
              acceptable_prefix=true
              ;;
            
            # These are the unacceptable branch prefixes
            *)
              acceptable_prefix=false
              ;;
          esac
          
          if [ "$acceptable_prefix" == "true" ] ; then
            echo "::notice ::Pull Request Granted with Branch Type: $branch_prefix"
          else
            echo "::error ::Wrong Branch Name"
            exit 1
          fi
